package com.strajag.brick_breaker.game;

public enum BrickType {

    STANDARD, PLUS, MINUS, DEATH, BALL_1X, BALL_2X, BALL_SPEED_PLUS, BALL_SPEED_MINUS, BALL_SIZE_PLUS, BALL_SIZE_MINUS, PLATFORM_SPEED_PLUS, PLATFORM_SPEED_MINUS, PLATFORM_SIZE_PLUS, PLATFORM_SIZE_MINUS
}
